import 'package:kky_ds/models/GNDivision.dart';

const GN_DIVISIONS = const [
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 77z7 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 2,
  //   divisionName: '162 A Kattankudy 06 South',
  //   gnName: 'ALF. Rifka',
  //   address: 'Multi Purpose Building, Deen Road, KKY-06',
  //   phone: '+94 766 068 969',
  //   gender: 'male',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
  // GNDivision(
  //   id: 1,
  //   divisionName: '162 Kattankudy 06',
  //   gnName: 'Mafasa Zulfihar Ali',
  //   address: 'Bawa Lane, Kattankudy-06',
  //   phone: '+94 777 897 747',
  //   gender: 'female',
  // ),
];
